# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Artemis properties.
spring:
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false
    broker-url: tcp://localhost:61616
---
# None of these properties will actually work as configured for this profile.
# But it is left here as an example of configuring for a production profile
# that will override the local configuration in the default profile.
spring:
  profiles: production
    
  artemis:
    broker-url: tcp://artemis.tacocloud.com:61617
    user: tacoweb
    password: l3tm31n