spring:
  datasource:
    url: jdbc:h2:mem:tacodb

---
spring:
  config:
    activate:
      on-profile: ldap
#  ldap:
#    embedded:
#      ldif: classpath:users.ldif
#      base-dn: dc=tacocloud,dc=com
#      port: 8389

