spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver
