server:
  port: 9090
  servlet:
    session:
      cookie:
        name: CLIENT_SESSION

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false
  application:
    name: tacocloud-admin
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: openid,writeIngredients,deleteIngredients
            client-authentication-method: client_secret_basic
        provider:
          tacocloud:
            issuer-uri: http://127.0.0.1:9000
