<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>sia</groupId>
        <artifactId>taco-cloud-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>ch13</artifactId>
    <version>0.0.13-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <tacocloud.version>0.0.13-SNAPSHOT</tacocloud.version>
    </properties>

    <modules>
        <module>ch13-tacocloud-mongodb</module>
        <module>ch13-tacocloud-cassandra</module>
        <module>ch13-tacocloud-r2dbc</module>
    </modules>

</project>