spring:
  application:
    name: api-taco
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: 53cr3t
  datasource:
    generate-unique-name: false
    name: tacocloud
  profiles:
    active: kafka

management:
  info:
    contact:
      email: mail
      phone: phone
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    broker-url: tcp://localhost:61616
    user: tacoweb
    password: letm31n
    mode: native
    embedded:
      enabled: false
  config:
    activate:
      on-profile: jms

---
spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
  config:
    activate:
      on-profile: kafka
