spring:
  security:
    user:
      name: admin
      password: password
  application:
    name: boot-admin-server

server:
  port: 9090

eureka:
  client:
    register-with-eureka: false

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
