spring:
  cloud:
    config:
      token: roottoken
  config:
    import: configserver:http://localhost:8888
  application:
    name: ingredient-service

management:
  endpoints:
    web:
      exposure:
        include: '*'