<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>sia</groupId>
    <artifactId>ch3</artifactId>
    <version>0.0.3-SNAPSHOT</version>
    <name>ch3</name>
    <description>ch3</description>
    <packaging>pom</packaging>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>21</java.version>
        <tacocloud.version>${project.version}</tacocloud.version>
    </properties>
    <modules>
        <module>tacos-jdbctemplate</module>
        <module>tacos-sd-jdbc</module>
        <module>tacos-sd-jpa</module>
    </modules>

</project>
