server:
  port: 9000

#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver


logging:
  level:
    org.springframework.security.oauth2.server.authorization.web.authentication: TRACE
    org:
      springframework:
        security:
          oauth2:
            core: DEBUG
            server:
              authorization: DEBUG
