server:
  port: 8888

spring:
  profiles:
    active: git, vault
  cloud:
    config:
      server:
        git:
          uri: http://localhost:3000/gogsuser/tacocloud-config
          order: 1
          default-label: master
        vault:
          host: localhost
          port: 8200
          order: 2
  application:
    name: config-server

encrypt:
  key: s3cr3t


